### ISSUE TITLE
datasetnya banyak yang tidak ada

### ISSUE THREAD

**Issue by iheind** [ardianumam/Data-Mining-and-Big-Data-Analytics-Book#1]
hallo, saya sudah beli bukunya mas. tapi datasetnya banyak yang tidak ada.
contoh: raw-flight-data.csv dan flights.csv tidak ada.

**Comment by ardianumam** [comment]
@iheind : masuk ke https://github.com/ardianumam/Data-Mining-and-Big-Data-Analytics-Book/tree/master/dataset, terus ada di readmenya. Soalnya ukurannya besar, jadi ada di eksternal storage, terus dipasang link downloadnya saja di readmenya tadi.

**Comment by iheind** [comment]
Oalah. Siap mas. Terima Kasih banyak untuk Ilmunya. Keep sharing.
